### PR TITLE
Added point cloud example issue #103

### PR DESCRIPTION
**Pull request by Gassepouille**
- Added ply model to the examples/models/ folder
- Created example for pointCloud intersection

Related to [#103 ](https://github.com/gkjohnson/three-mesh-bvh/issues/103)

### CODE REVIEW

**Comment by gkjohnson** [comment]
Awesome, thank you! I'll take a deeper look at the code this weekend. Here's a live link to the demo:

https://raw.githack.com/Gassepouille/three-mesh-bvh/point-cloud-intersection-example/example/bundle/pointCloudIntersection.html

A couple quick comments -- the demo logs an error until the PLY model has been loaded. Can we guard against that in the render loop until the model is available? And where did the point cloud model come from? Is there an attribution we should give?

Thanks again!

**Comment by Gassepouille** [comment]
Ahh yeah, of course, sorry about that, I didn't see the error coming through

>  And where did the point cloud model come from? Is there an attribution we should give?

The point cloud comes from a scan done by one of my colleague and it seems to be under "CC AttributionCreative Commons Attribution license". 
Not too sure how it works, but I guess we could add the "Scan done with/by Sitescape" with the link to the scan on sketchfab and that should work. What do you think ? Or we can try to find a scan that is completely free of anything ?

**Comment by gkjohnson** [comment]
> it seems to be under "CC AttributionCreative Commons Attribution license".
> ... with the link to the scan on sketchfab and that should work.

Yeah if we could add attribution and link to the sketchfab model that would be great. Similar to what we're doing for the model in the [physics](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/physics.html) demo.

**Comment by gkjohnson** [comment]
Also it looks like the lint checks have failed -- you should be able to run `npx eslint \"./example/*.js\" --fix` to automatically fix them all. Otherwise I can fix them once it's merged!

**Comment by Gassepouille** [comment]
Alright, done, and done ! Let me know if anything else is needed :D

**Comment by gkjohnson** [comment]
Great, thank you! There are a couple things that can be improved in the raycasting so I'll let you know when I make a PR with some of those so you can leverage them, as well.

Thanks again!

**Comment by Gassepouille** [comment]
No worries, you're the one that needs to be praised with such an awesome project!

**Pull request merged**
