### PR TITLE
Support building BVH for geometries with material groups

### LINKED ISSUE #66: BVH construction doesn't work when geometries have groups
Today I learned that three.js `BufferGeometry` can have [`groups`](https://threejs.org/docs/#api/en/core/BufferGeometry.groups), which are ranges of the index that are meant to be drawn with a different material. For example, you can set the first half of the index to be drawn with one material, and the second half to be drawn with another.

This presents a problem for us because if we reorder the index, we are invalidating the group ranges, so the resulting geometry will be drawn with the wrong materials on different parts of the model.

There are maybe three reasonable things we could do to address this:

1. Don't construct BVHs for geometries with groups. Perhaps we could offer functionality to "ungroup" grouped geometries.
2. Add a layer of indirection like our `tris` which we retain in memory permanently, so that we leave the index alone and store ranges of `tris` in our tree nodes.
3. Create one BVH "root" for each group which only stores and reorders indices in that group. That way, we will still scramble up the index, but the integrity of the groups will remain. When we raycast, raycast down all the roots (minding bounding boxes.)

I think solution number 3 sounds pretty easy and has no real downsides (raycasting might be very slightly more expensive, but that was also true for solution 2, and if someone doesn't like that, they can ungroup their geometries), and we should implement it.

### PR DESCRIPTION
**Pull request by mqp**
Resolves #66. Now the BVH respects [groups](https://threejs.org/docs/#api/en/core/BufferGeometry.groups) on geometries, instead of mucking up the index and rendering the groups meaningless. This implements "option 3" as discussed in the linked issue. It seems to work well on some test Hubs scenes that have geometries with groups. There's no measurable change in performance for geometries that don't have groups, as it just adds one trivial layer of processing and indirection at the top of raycasting.

### CODE REVIEW

**Comment by gkjohnson** [comment]
Looks great! I'll plan to add the option in #67 in another PR.

Can we add a test for a geometry with groups?

Thanks!

**Comment by mqp** [comment]
Sure, I'll fix up the tests in two ways:

- By adding an example that verifies that in geometries with groups, raycasting with a BVH still returns the same results as raycasting without a BVH.
- By adding an additional test that verifies that whenever you build a BVH, for all index groups with bounds `start` and `end`, the set of all triangle indices `{index[i]: i ∈ [start, end]}` is identical before and after BVH construction.

**Comment by mqp** [comment]
Actually, when I try the raycasting test suite with grouped geometry, it doesn't pass, so either I made a mistake in the test or there is a bug in my implementation. I don't know which yet.

**Comment by mqp** [comment]
OK, seems like things are working well.

**Comment by gkjohnson** [comment]
Looks great, thanks!

**Pull request merged**
