### PR TITLE
[workers] - fix name in warning

### PR DESCRIPTION
**Pull request by dbuck**
^ Should this instead be removed here and from main readme?

### CODE REVIEW

**Comment by gkjohnson** [comment]
Thanks! I will plan to remove it entirely in an upcoming release but it's good to fix the name for now.

> from main readme?

Heh I forgot it was still mentioned in the readme 😅. Instead of removing it from the readme entirely can we change it to document `GenerateMeshBVHWorker`, instead? The signature and docs for `GenerateMeshBVHWorker.run` should be the same as `generateAsync` and we can change the "Extra Functions" heading to be "GenerateMeshBVHWorker".

Thanks again! Sorry if it caused confusion.

**Comment by dbuck** [comment]
Shifting the description to be next to the existing worker code snippet seemed the call

**Comment by gkjohnson** [comment]
> Shifting the description to be next to the existing worker code snippet seemed the call

I'd prefer to keep the documentation for the class down in the "API" section as I'd suggested so it's consistent with the rest of the docs. The snippets in the "Use" section are meant to show quick starts for basic features of the library while the "API" section is intended to document the interfaces, arguments, and return types of the available classes. The async generation snippet doesn't, for example, show that the `generate` function takes an "options" argument or that a `terminate` function exists at all.

**Comment by gkjohnson** [comment]
I'll go ahead and update the README -- thanks again for pointing it out and fixing the warning!

**Pull request merged**
